version: "3"

services:
  app:
    image: nextjs-with-docker-dev
    build: .
    ports:
      - 3030:3030
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
